// Experiments list


export const MOVIES_REQUEST = 'MOVIES_REQUEST';
export const MOVIES_SUCCESS = 'MOVIES_SUCCESS';
export const MOVIES_FAILURE = 'MOVIES_FAILURE';
export const MOVIES_FAVOURITE = 'MOVIES_FAVOURITE';
export const MOVIE_ACTIVE= 'MOVIE_ACTIVE';
